#!/bin/bash

# Path to the colors.sh file generated by pywal
source "${HOME}/.cache/wal/colors.sh"

# Path to your i3 config file
I3_CONFIG="${HOME}/.config/i3/config"

# Replace colors in the i3 config
sed -i "s/\$bg-color/$background/g" $I3_CONFIG
sed -i "s/\$text-color/$foreground/g" $I3_CONFIG
sed -i "s/\$border-color/$color1/g" $I3_CONFIG

# Reload i3
# i3-msg reload
